"use client";
import { useState } from "react";
import type { Locale } from "@/lib/i18n";
import { ActionButton } from "@/components/ui/action-button";
import { FormError } from "@/components/ui/form-error";
import { FormField, TextInput } from "@/components/ui/form-field";

export function InviteSellerForm({ locale, onInvite }: { locale: Locale; onInvite: (values: { fullName: string; email: string; phone: string }) => Promise<{ emailSent: boolean; idempotentReplay: boolean }> }) {
  const tr = locale === "tr"; const [values, setValues] = useState({ fullName: "", email: "", phone: "" }); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!values.fullName.trim() || !values.phone.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim())) { setError(tr ? "Ad, geçerli e-posta ve telefon gereklidir." : "Full name, valid email and phone are required."); return; } setSaving(true); setError(""); setSuccess(""); try { const result = await onInvite({ fullName: values.fullName.trim(), email: values.email.trim(), phone: values.phone.trim() }); setSuccess(result.emailSent ? (tr ? "Davet e-postası gönderildi." : "Invitation email sent.") : (tr ? "Mevcut erişim kaydedildi." : "Existing account access saved.")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to send invite."); } finally { setSaving(false); } };
  return <form onSubmit={(event) => void submit(event)} className="space-y-4 p-5 sm:p-7"><p className="text-xs leading-relaxed text-zinc-500">{tr ? "Satıcı güvenli giriş bağlantısını e-posta ile alır." : "The seller receives a secure sign-in link by email."}</p><FormField label={tr ? "Ad soyad" : "Full name"}><TextInput aria-label="Full name" value={values.fullName} onChange={(event) => setValues({ ...values, fullName: event.target.value })} /></FormField><FormField label="Email"><TextInput aria-label="Email" type="email" value={values.email} onChange={(event) => setValues({ ...values, email: event.target.value })} /></FormField><FormField label={tr ? "Telefon" : "Phone"}><TextInput aria-label="Phone" value={values.phone} onChange={(event) => setValues({ ...values, phone: event.target.value })} /></FormField><FormError>{error}</FormError>{success && <p role="status" className="text-xs text-emerald-300">✓ {success}</p>}<ActionButton type="submit" className="w-full" loading={saving}>{saving ? (tr ? "Gönderiliyor…" : "Sending…") : (tr ? "Davet gönder" : "Send invitation")}</ActionButton></form>;
}
