"use client";
import { useEffect, useState } from "react";
import type { Supplier } from "@/features/suppliers/model/types";

export function SupplierManager({ suppliers, onSave, onArchive }: { suppliers: Supplier[]; onSave: (values: { supplier?: Supplier; name: string; phone: string; notes: string }) => Promise<void>; onArchive: (supplier: Supplier) => Promise<void> }) {
  const [selected, setSelected] = useState<Supplier | undefined>(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { setName(selected?.name ?? ""); setPhone(selected?.phone ?? ""); setNotes(selected?.notes ?? ""); }, [selected]);
  const submit = async () => { if (!name.trim()) { setError("Supplier name is required."); return; } setSaving(true); setError(""); try { await onSave({ supplier: selected, name, phone, notes }); setSelected(undefined); setName(""); setPhone(""); setNotes(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save supplier."); } finally { setSaving(false); } };
  return <div className="grid gap-5 p-5 sm:grid-cols-[1.1fr_.9fr] sm:p-7"><div className="divide-y divide-zinc-800 rounded-xl border border-zinc-800">{suppliers.length ? suppliers.map((supplier) => <div key={supplier.id} className="flex items-center gap-3 p-3"><button type="button" onClick={() => setSelected(supplier)} className="min-w-0 flex-1 text-left"><span className="block truncate text-xs text-zinc-200">{supplier.name}</span><span className="mt-1 block text-[10px] text-zinc-600">{supplier.phone || "—"}</span></button><button type="button" onClick={() => void onArchive(supplier)} className="rounded-md border border-zinc-700 px-2 py-1 text-[10px] text-zinc-400">{supplier.isActive ? "Archive" : "Restore"}</button></div>) : <p className="p-5 text-xs text-zinc-600">No suppliers yet.</p>}</div><div><p className="text-xs font-semibold text-zinc-200">{selected ? "Edit supplier" : "New supplier"}</p><label className="mt-4 block text-[10px] uppercase tracking-[.14em] text-zinc-500">Name<input aria-label="Supplier name" value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-zinc-800 bg-zinc-900 px-3 text-xs text-zinc-100 outline-none focus:border-violet-500" /></label><label className="mt-3 block text-[10px] uppercase tracking-[.14em] text-zinc-500">Phone<input aria-label="Supplier phone" value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-zinc-800 bg-zinc-900 px-3 text-xs text-zinc-100 outline-none focus:border-violet-500" /></label><label className="mt-3 block text-[10px] uppercase tracking-[.14em] text-zinc-500">Notes<textarea aria-label="Supplier notes" value={notes} onChange={(event) => setNotes(event.target.value)} className="mt-2 w-full rounded-lg border border-zinc-800 bg-zinc-900 p-3 text-xs text-zinc-100 outline-none focus:border-violet-500" /></label>{error && <p role="alert" className="mt-3 text-xs text-red-300">{error}</p>}<button type="button" disabled={saving} onClick={() => void submit()} className="mt-4 h-10 w-full rounded-lg bg-violet-600 text-xs font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save supplier"}</button></div></div>;
}
