import type { Locale } from "@/lib/i18n";

export const catalogCopy = {
  en: {
    productDetails: "Product details",
    openPhotoFullscreen: "Open photo fullscreen",
    photoAlt: (name: string, index: number) => `${name}, view ${index}`,
    enlargedPhotoAlt: (name: string, index: number) => `${name}, enlarged view ${index}`,
    noPhotos: "No photos yet",
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
    uploadingPhotos: "Uploading photos…",
    addPhotos: "Add photos",
    removePhoto: "Remove this photo",
    removePhotoConfirm: "Remove this photo from this product? This cannot be undone. Historical sale photos remain protected.",
    removingPhoto: "Removing…",
    removePhotoError: "This photo could not be removed. Please try again.",
    uploadHint: "JPEG, PNG or WebP · up to 8 MB each",
    uploadTypeError: "Use JPEG, PNG or WebP photos only.",
    uploadSizeError: "Each photo must be 8 MB or smaller.",
    uploadAccessError: "You do not have permission to add photos for this product.",
    uploadGenericError: "Photos could not be uploaded. Please try again.",
    totalStock: "Total stock",
    pieces: (count: number) => `${count} pcs`,
    sellPrice: "Sell price",
    color: "Color",
    availableSizes: "Available sizes",
    stockByVariant: "Stock by variant",
    supplier: "Supplier",
    barcode: "Barcode",
    gender: "Gender",
    genderNames: { women: "Women", men: "Men", unisex: "Unisex" },
    variants: "Variants",
    sellThisProduct: "Sell this product",
    editProduct: "Edit product",
    productCode: "Product code",
    saveCode: "Save code",
    cancelEdit: "Cancel",
    savingCode: "Saving…",
    codeRequired: "Enter a product code.",
    codeSaved: "Product code updated.",
    codeAccessError: "Only an Owner can edit product codes.",
    codeDuplicateError: "This product code is already used in this store.",
    codeGenericError: "The product code could not be saved. Please try again.",
    barcodeUnchanged: "Barcode is not changed here.",
    editProductCode: "Edit product code",
    productName: "Name",
    lowStockThreshold: "Low-stock threshold",
    purchaseCost: "Purchase cost",
    purchaseCurrency: "Currency",
    detailsScope: "Applies to all colours and sizes of this Product code; past sales and receipts stay unchanged.",
    saveDetails: "Save details",
    savingDetails: "Saving…",
    detailsValidation: "Enter a name, whole threshold and valid purchase cost.",
    detailsGenericError: "Product details could not be saved. Please try again.",
    archiveProduct: "Archive product",
    restoreProduct: "Restore product",
    archiveConfirm: "Archive this product? It will be hidden from normal inventory and sales, while its history stays intact.",
    archiveConfirmAction: "Archive",
    cancelArchive: "Keep active",
    archivingProduct: "Saving…",
    archiveAccessError: "Only an Owner can archive or restore products.",
    archiveGenericError: "The product status could not be saved. Please try again.",
    photoViewer: "Photo viewer",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    closePhotoViewer: "Close photo viewer",
  },
  tr: {
    productDetails: "Ürün detayları",
    openPhotoFullscreen: "Fotoğrafı tam ekran aç",
    photoAlt: (name: string, index: number) => `${name}, görünüm ${index}`,
    enlargedPhotoAlt: (name: string, index: number) => `${name}, büyütülmüş görünüm ${index}`,
    noPhotos: "Henüz fotoğraf yok",
    previousPhoto: "Önceki fotoğraf",
    nextPhoto: "Sonraki fotoğraf",
    uploadingPhotos: "Fotoğraflar yükleniyor…",
    addPhotos: "Fotoğraf ekle",
    removePhoto: "Bu fotoğrafı kaldır",
    removePhotoConfirm: "Bu fotoğraf üründen kaldırılsın mı? Bu işlem geri alınamaz. Geçmiş satış fotoğrafları korunur.",
    removingPhoto: "Kaldırılıyor…",
    removePhotoError: "Bu fotoğraf kaldırılamadı. Lütfen tekrar deneyin.",
    uploadHint: "JPEG, PNG veya WebP · her biri en fazla 8 MB",
    uploadTypeError: "Yalnızca JPEG, PNG veya WebP fotoğrafları kullanın.",
    uploadSizeError: "Her fotoğraf en fazla 8 MB olabilir.",
    uploadAccessError: "Bu ürüne fotoğraf ekleme izniniz yok.",
    uploadGenericError: "Fotoğraflar yüklenemedi. Lütfen tekrar deneyin.",
    totalStock: "Toplam stok",
    pieces: (count: number) => `${count} adet`,
    sellPrice: "Satış fiyatı",
    color: "Renk",
    availableSizes: "Mevcut bedenler",
    stockByVariant: "Varyant bazında stok",
    supplier: "Tedarikçi",
    barcode: "Barkod",
    gender: "Cinsiyet",
    genderNames: { women: "Kadın", men: "Erkek", unisex: "Unisex" },
    variants: "Varyantlar",
    sellThisProduct: "Bu ürünü sat",
    editProduct: "Ürünü düzenle",
    productCode: "Ürün kodu",
    saveCode: "Kodu kaydet",
    cancelEdit: "İptal",
    savingCode: "Kaydediliyor…",
    codeRequired: "Bir ürün kodu girin.",
    codeSaved: "Ürün kodu güncellendi.",
    codeAccessError: "Ürün kodlarını yalnızca bir sahip düzenleyebilir.",
    codeDuplicateError: "Bu ürün kodu bu mağazada zaten kullanılıyor.",
    codeGenericError: "Ürün kodu kaydedilemedi. Lütfen tekrar deneyin.",
    barcodeUnchanged: "Barkod burada değiştirilmez.",
    editProductCode: "Ürün kodunu düzenle",
    productName: "Ad",
    lowStockThreshold: "Düşük stok eşiği",
    purchaseCost: "Alış maliyeti",
    purchaseCurrency: "Para birimi",
    detailsScope: "Bu ürün kodunun tüm renk ve bedenlerine uygulanır; geçmiş satışlar ve kabuller değişmez.",
    saveDetails: "Bilgileri kaydet",
    savingDetails: "Kaydediliyor…",
    detailsValidation: "Bir ad, tam sayı eşik ve geçerli alış maliyeti girin.",
    detailsGenericError: "Ürün bilgileri kaydedilemedi. Lütfen tekrar deneyin.",
    archiveProduct: "Ürünü arşivle",
    restoreProduct: "Ürünü geri yükle",
    archiveConfirm: "Bu ürün arşivlensin mi? Geçmişi korunur, normal stok ve satıştan gizlenir.",
    archiveConfirmAction: "Arşivle",
    cancelArchive: "Aktif tut",
    archivingProduct: "Kaydediliyor…",
    archiveAccessError: "Ürünleri yalnızca bir sahip arşivleyebilir veya geri yükleyebilir.",
    archiveGenericError: "Ürün durumu kaydedilemedi. Lütfen tekrar deneyin.",
    photoViewer: "Fotoğraf görüntüleyici",
    zoomOut: "Uzaklaştır",
    zoomIn: "Yakınlaştır",
    closePhotoViewer: "Fotoğraf görüntüleyiciyi kapat",
  },
} satisfies Record<Locale, object>;

export function productCardErrorMessage(message: string, locale: Locale) {
  const text = catalogCopy[locale];
  if (/JPEG, PNG or WebP/i.test(message)) return text.uploadTypeError;
  if (/8 MB/i.test(message)) return text.uploadSizeError;
  if (/No access|permission|row-level security/i.test(message)) return text.uploadAccessError;
  return text.uploadGenericError;
}

export function productArchiveErrorMessage(message: string, locale: Locale) {
  const text = catalogCopy[locale];
  if (/Only an Owner|No access|permission|row-level security/i.test(message)) return text.archiveAccessError;
  return text.archiveGenericError;
}

export function productCodeErrorMessage(message: string, locale: Locale) {
  const text = catalogCopy[locale];
  if (/Only an Owner|No access|permission|row-level security/i.test(message)) return text.codeAccessError;
  if (/already used|duplicate|unique/i.test(message)) return text.codeDuplicateError;
  return text.codeGenericError;
}
