"use client";
import { useEffect, useState } from "react";
import type { AuditCategory, AuditLogItem } from "@/features/audit/model/types";
import { copy, type Locale } from "@/lib/i18n";

const categories: AuditCategory[] = ["sale", "receipt", "fx", "image", "seller", "inventory", "supplier", "catalog", "other"];
export function AuditLog({ load, locale }: { load: (page: number, category?: AuditCategory) => Promise<{ items: AuditLogItem[]; hasMore: boolean }>; locale: Locale }) {
  const text = copy[locale];
  const [page, setPage] = useState(1); const [category, setCategory] = useState<AuditCategory | undefined>(); const [items, setItems] = useState<AuditLogItem[]>([]); const [hasMore, setHasMore] = useState(false); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { let alive = true; setState("loading"); void load(page, category).then((result) => { if (alive) { setItems(result.items); setHasMore(result.hasMore); setState("ready"); } }).catch(() => alive && setState("error")); return () => { alive = false; }; }, [load, page, category]);
  return <div className="space-y-4 p-5 sm:p-7"><div className="flex flex-wrap gap-2"><button onClick={() => { setCategory(undefined); setPage(1); }} className={`rounded-lg border px-3 py-2 text-[10px] ${!category ? "border-violet-500 bg-violet-500/10 text-violet-200" : "border-zinc-800 text-zinc-500"}`}>{text.auditAll}</button>{categories.map((item) => <button key={item} onClick={() => { setCategory(item); setPage(1); }} className={`rounded-lg border px-3 py-2 text-[10px] ${category === item ? "border-violet-500 bg-violet-500/10 text-violet-200" : "border-zinc-800 text-zinc-500"}`}>{text.auditCategories[item]}</button>)}</div>{state === "loading" && <p className="py-8 text-center text-xs text-zinc-500">{text.auditLoading}</p>}{state === "error" && <p role="alert" className="py-8 text-center text-xs text-red-300">{text.auditError}</p>}{state === "ready" && (items.length ? <div className="divide-y divide-zinc-800/70 rounded-xl border border-zinc-800">{items.map((item) => <div key={item.id} className="flex gap-3 p-3"><span className="rounded-md border border-zinc-800 bg-zinc-900 px-2 py-1 text-[10px] text-zinc-400">{text.auditCategories[item.category]}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-zinc-200">{item.action}</p><p className="mt-1 text-[10px] text-zinc-600">{item.actorName} · {new Date(item.createdAt).toLocaleString(locale === "tr" ? "tr-TR" : "en-IE")}</p></div></div>)}</div> : <p className="py-8 text-center text-xs text-zinc-600">{text.auditEmpty}</p>)}<div className="flex justify-between"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="text-xs text-zinc-400 disabled:opacity-30">{text.previous}</button><span className="text-xs text-zinc-600">{page}</span><button disabled={!hasMore} onClick={() => setPage((value) => value + 1)} className="text-xs text-zinc-400 disabled:opacity-30">{text.next}</button></div></div>;
}
