import { ArrowUpRight, ReceiptText, TrendingUp, WalletCards, type LucideIcon } from "lucide-react";
import { LowStockCarousel } from "@/components/low-stock-carousel";
import { SellerGoalCard } from "@/features/seller-goals/ui/seller-goal-card";
import type { Locale } from "@/lib/i18n";
import type { Period, Product, Role, Seller } from "@/lib/types";

type Metrics = { revenue: number; margin: number; count: number };
type RankedSeller = Seller & { revenue: number; count: number };
type Labels = { revenue: string; sales: string; grossMargin: string; myResult: string; unitsShort: string; todayDelta: string; periodDelta: string; itemsDelta: string; ofRevenue: string; salesTrend: string; lastSevenDays: string; sellerResults: string; revenueRanking: string; manage: string; liveData?: string };
const money = (value: number, locale: Locale) => new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
const integer = (value: number, locale: Locale) => new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-US").format(value);
function MetricCard({ label, value, delta, icon: Icon, accent = false }: { label: string; value: string; delta: string; icon: LucideIcon; accent?: boolean }) { return <article className={`panel metric-glow relative min-w-0 overflow-hidden rounded-2xl p-5 ${accent ? "purple-shadow border-violet-500/30" : ""}`}><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{label}</p><p className="mt-3 text-2xl font-semibold text-zinc-50">{value}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-emerald-400"><ArrowUpRight size={14} />{delta}</p></div><Icon size={19} /></div></article>; }
export function Overview({ role, period, metrics, chartData, rankedSellers, products, live, labels, onManageTeam, locale = "en" }: { role: Role; period: Period; metrics: Metrics; chartData: { label: string; value: number }[]; rankedSellers: RankedSeller[]; products: Product[]; live: boolean; labels: Labels; onManageTeam: () => void; locale?: Locale }) {
  const max = Math.max(...chartData.map((day) => day.value), 1);
  const liveLabel = labels.liveData ?? "Live data";
  return <><div className={`mt-4 grid gap-3 ${role === "owner" ? "grid-cols-2 xl:grid-cols-4" : "grid-cols-1 sm:grid-cols-3"}`}><MetricCard label={labels.revenue} value={money(metrics.revenue, locale)} delta={live ? liveLabel : period === "day" ? labels.todayDelta : labels.periodDelta} icon={WalletCards} accent /><MetricCard label={labels.sales} value={`${integer(metrics.count, locale)} ${labels.unitsShort}`} delta={live ? liveLabel : labels.itemsDelta} icon={ReceiptText} /><MetricCard label={role === "owner" ? labels.grossMargin : labels.myResult} value={money(metrics.margin, locale)} delta={`${metrics.revenue ? Math.round(metrics.margin / metrics.revenue * 100) : 0}% ${labels.ofRevenue}`} icon={TrendingUp} />{role === "owner" && <LowStockCarousel products={products} locale={locale} />}</div><section id="sales" className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.75fr)]"><article className="panel rounded-2xl p-5"><p className="text-sm font-semibold">{labels.salesTrend}</p><p className="mt-1 text-xs text-zinc-600">{labels.lastSevenDays}</p><div className="mt-8 flex h-52 items-end gap-2">{chartData.map((day) => <div key={day.label} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-violet-500" style={{ height: `${Math.max(4, day.value / max * 100)}%` }} /><span className="text-[10px] text-zinc-600">{day.label}</span></div>)}</div></article>{role === "owner" ? <article id="team" className="panel rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-sm font-semibold">{labels.sellerResults}</p><p className="text-xs text-zinc-600">{labels.revenueRanking}</p></div><button type="button" onClick={onManageTeam} className="text-violet-400">{labels.manage}</button></div>{rankedSellers.slice(0, 4).map((seller) => <div key={seller.id} className="mt-4 flex justify-between text-xs"><span>{seller.name}</span><span>{money(seller.revenue, locale)}</span></div>)}</article> : <SellerGoalCard actual={metrics.revenue} period={period} />}</section></>;
}
