"use client";

import { useState } from "react";
import { ArrowUpRight, ReceiptText, TrendingUp, WalletCards, X, type LucideIcon } from "lucide-react";
import { LowStockCarousel } from "@/components/low-stock-carousel";
import { SellerGoalCard } from "@/features/seller-goals/ui/seller-goal-card";
import type { Locale } from "@/lib/i18n";
import type { Period, Product, Role, Seller } from "@/lib/types";

type Metrics = { revenue: number; margin: number; count: number };
type RankedSeller = Seller & { revenue: number; count: number };
type ChartDay = { label: string; value: number };
type Labels = { revenue: string; sales: string; grossMargin: string; myResult: string; unitsShort: string; todayDelta: string; periodDelta: string; itemsDelta: string; ofRevenue: string; salesTrend: string; lastSevenDays: string; sellerResults: string; revenueRanking: string; manage: string; liveData?: string };
type SelectionSource = "tap" | "hover" | "focus";

const money = (value: number, locale: Locale) => new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
const integer = (value: number, locale: Locale) => new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-US").format(value);

function MetricCard({ label, value, delta, icon: Icon, accent = false }: { label: string; value: string; delta: string; icon: LucideIcon; accent?: boolean }) {
  return <article className={`panel metric-glow relative min-w-0 overflow-hidden rounded-2xl p-5 ${accent ? "purple-shadow border-violet-500/30" : ""}`}><div className="relative z-10"><div className="flex items-start justify-between gap-3"><p className="min-w-0 text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{label}</p><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${accent ? "border-violet-400/25 bg-violet-500/15 text-violet-300" : "border-zinc-800 bg-zinc-900 text-zinc-400"}`}><Icon size={19} strokeWidth={1.8} /></span></div><p data-testid="metric-value" className="mt-3 break-words text-[clamp(1.25rem,6vw,2rem)] font-semibold leading-tight tracking-[-0.04em] text-zinc-50">{value}</p><div className="mt-3 flex items-center gap-1.5 text-xs font-medium text-emerald-400"><ArrowUpRight size={14} /><span>{delta}</span></div></div></article>;
}

function SalesTrendChart({ chartData, chartMax, locale }: { chartData: ChartDay[]; chartMax: number; locale: Locale }) {
  const [selection, setSelection] = useState<{ index: number; source: SelectionSource } | null>(null);
  const tr = locale === "tr";
  const copy = tr
    ? { selected: "Seçilen gün", hint: "Tutarı görmek için bir güne dokunun", close: "Seçimi kapat", choose: "Gün cirosunu göster" }
    : { selected: "Selected day", hint: "Tap a day to see its amount", close: "Close selection", choose: "Show day revenue" };
  const selectedDay = selection ? chartData[selection.index] : null;
  const chooseByTap = (index: number) => setSelection((current) => current?.source === "tap" && current.index === index ? null : { index, source: "tap" });
  const revealByHover = (index: number) => setSelection((current) => current?.source === "tap" ? current : { index, source: "hover" });
  const clearHover = () => setSelection((current) => current?.source === "hover" ? null : current);
  const revealByFocus = (index: number) => setSelection((current) => current?.source === "tap" ? current : { index, source: "focus" });
  const clearFocus = () => setSelection((current) => current?.source === "focus" ? null : current);

  return <div className="mt-5 min-w-0"><div className="min-h-12 rounded-xl border border-zinc-800 bg-zinc-950/40 px-3 py-2" aria-live="polite">{selectedDay ? <div className="flex min-w-0 items-center justify-between gap-2"><p className="min-w-0 text-xs text-zinc-300"><span className="text-zinc-500">{copy.selected}: </span><span className="font-medium text-zinc-100">{selectedDay.label}</span><span className="mx-1.5 text-zinc-600">·</span><strong>{money(selectedDay.value, locale)}</strong></p><button type="button" onClick={() => setSelection(null)} className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-zinc-700 text-zinc-400 transition hover:border-zinc-500 hover:text-white" aria-label={copy.close}><X size={15} /></button></div> : <p className="pt-1 text-xs text-zinc-500">{copy.hint}</p>}</div><div className="chart-grid mt-3 flex h-52 items-end gap-2 rounded-lg px-1 pt-5 sm:gap-4" aria-label={tr ? "Son yedi gün satış cirosu" : "Revenue for the last seven days"}>{chartData.map((day, index) => { const height = Math.max(4, day.value / chartMax * 100); const isSelected = selection?.index === index; return <div key={day.label} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><button type="button" onClick={() => chooseByTap(index)} onMouseEnter={() => revealByHover(index)} onMouseLeave={clearHover} onFocus={() => revealByFocus(index)} onBlur={clearFocus} aria-pressed={isSelected} aria-label={`${day.label}: ${money(day.value, locale)}. ${copy.choose}`} className={`relative flex h-full w-full items-end justify-center rounded-md outline-none transition focus-visible:ring-2 focus-visible:ring-violet-300 focus-visible:ring-offset-2 focus-visible:ring-offset-zinc-950 ${isSelected ? "bg-violet-500/10" : "sales-trend-bar-hitarea"}`}><span className={`pointer-events-none absolute bottom-[calc(var(--bar-height)+8px)] z-10 -translate-x-1/2 whitespace-nowrap rounded-md border border-zinc-700 bg-zinc-800 px-2 py-1 text-[10px] font-medium text-white transition-opacity ${isSelected ? "opacity-100" : "opacity-0"}`} style={{ left: "50%", ["--bar-height" as string]: `${Math.max(6, day.value / chartMax * 100)}%` }}>{money(day.value, locale)}</span><span className="w-full max-w-11 rounded-t-md bg-gradient-to-t from-violet-700 to-violet-400" style={{ height: `${height}%`, opacity: day.value ? 1 : .18 }} /></button><span className="text-[10px] text-zinc-600">{day.label}</span></div>; })}</div></div>;
}

export function Overview({ role, period, metrics, chartData, rankedSellers, products, live, labels, onManageTeam, locale = "en" }: { role: Role; period: Period; metrics: Metrics; chartData: ChartDay[]; rankedSellers: RankedSeller[]; products: Product[]; live: boolean; labels: Labels; onManageTeam: () => void; locale?: Locale }) {
  const chartMax = Math.max(...chartData.map((day) => day.value), 1);
  const liveLabel = labels.liveData ?? "Live data";
  return <><div className={`mt-4 grid gap-3 ${role === "owner" ? "grid-cols-2 xl:grid-cols-4" : "grid-cols-1 sm:grid-cols-3"}`}><MetricCard label={labels.revenue} value={money(metrics.revenue, locale)} delta={live ? liveLabel : period === "day" ? labels.todayDelta : labels.periodDelta} icon={WalletCards} accent /><MetricCard label={labels.sales} value={`${integer(metrics.count, locale)} ${labels.unitsShort}`} delta={live ? liveLabel : labels.itemsDelta} icon={ReceiptText} /><MetricCard label={role === "owner" ? labels.grossMargin : labels.myResult} value={money(metrics.margin, locale)} delta={`${metrics.revenue ? Math.round((metrics.margin / metrics.revenue) * 100) : 0}% ${labels.ofRevenue}`} icon={TrendingUp} />{role === "owner" && <LowStockCarousel products={products} locale={locale} />}</div><section id="sales-trend" className="mt-4 scroll-mt-24 grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.75fr)]"><article className="panel min-w-0 rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">{labels.salesTrend}</p><p className="mt-1 text-xs text-zinc-600">{labels.lastSevenDays}</p></div><div className="flex items-center gap-2 text-[10px] text-zinc-500"><span className="h-2 w-2 rounded-full bg-violet-500" /> {labels.revenue}</div></div><SalesTrendChart chartData={chartData} chartMax={chartMax} locale={locale} /></article>{role === "owner" ? <article id="team" className="panel scroll-mt-24 rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold">{labels.sellerResults}</p><p className="mt-1 text-xs text-zinc-600">{labels.revenueRanking}</p></div><button type="button" onClick={onManageTeam} className="text-[11px] font-medium text-violet-400">{labels.manage}</button></div><div className="mt-5 space-y-4">{rankedSellers.slice(0, 4).map((seller, index) => <div key={seller.id} className="flex items-center gap-3"><span className="w-3 text-[10px] text-zinc-700">{String(index + 1).padStart(2, "0")}</span><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-zinc-800 text-[10px] font-bold text-zinc-300">{seller.initials}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate text-xs font-medium text-zinc-300">{seller.name}</p><p className="text-xs font-semibold text-zinc-100">{money(seller.revenue, locale)}</p></div></div><span className="text-[10px] text-zinc-600">{seller.count} {labels.unitsShort}</span></div>)}</div></article> : <SellerGoalCard actual={metrics.revenue} period={period} locale={locale} />}</section></>;
}
