import type { Locale } from "@/lib/i18n";

export const receiptCopy = {
  en: {
    dialogTitle: "Receive products",
    dialogEyebrow: "Manual receipt",
    introTitle: "Fast size-based receipt",
    introDescription: "Enter the model once, choose a color, then set quantities directly for every size received.",
    modelCode: "1 · Product code / Ürün Kodu",
    modelCodePlaceholder: "KM-9902",
    modelCodeInvalidCharacters: "Product code contains a non-printing character. Remove it and try again.",
    existingModel: "Existing model selected · shared details are locked. Add only a color, sizes and receipt cost.",
    changeModel: "Choose another product",
    productName: "Product name",
    productNamePlaceholder: "Silk Midi Dress",
    brand: "Brand",
    brandPlaceholder: "Zimmermann",
    category: "Category",
    categoryPlaceholder: "Dresses",
    supplier: "Supplier",
    supplierPlaceholder: "PINO",
    barcode: "Model barcode (optional)",
    barcodePlaceholder: "869000700001",
    variantBarcode: "Variant barcode (optional)",
    gender: "Gender",
    genderNames: { women: "Women", men: "Men", unisex: "Unisex" },
    purchaseCost: "Purchase cost",
    currency: "Currency",
    color: "2 · Color",
    colorPlaceholder: "Type or choose a color",
    sizes: "3 · Sizes and quantity",
    sizesHelp: "Tap every received size, then adjust its quantity.",
    selectedPieces: (count: number) => `${count} pcs selected`,
    otherSize: "Other size",
    addSize: "Add size",
    quantity: "Quantity",
    removeSize: (size: string) => `Remove size ${size}`,
    saveColor: "Save this color and add another",
    draftHeading: (count: number) => `Receipt draft · ${count} size rows`,
    draftLine: (color: string, size: string) => `${color} · size ${size}`,
    pieces: (count: number) => `${count} pcs`,
    removeDraftLine: (color: string, size: string) => `Remove ${color}, size ${size}`,
    requiredFieldsHelp: "Fill in every required product field above. Gray examples are hints, not entered values.",
    cancel: "Cancel",
    saving: "Saving…",
    receiveItems: (count: number) => `Receive ${count} ${count === 1 ? "item" : "items"}`,
  },
  tr: {
    dialogTitle: "Ürün kabul et",
    dialogEyebrow: "Manuel kabul",
    introTitle: "Hızlı beden bazlı kabul",
    introDescription: "Modeli bir kez girin, rengi seçin ve kabul edilen her bedenin adedini doğrudan belirleyin.",
    modelCode: "1 · Ürün kodu / Product code",
    modelCodePlaceholder: "KM-9902",
    modelCodeInvalidCharacters: "Ürün kodunda görünmeyen bir karakter var. Kaldırıp tekrar deneyin.",
    existingModel: "Mevcut model seçildi · ortak bilgiler kilitli. Yalnızca renk, beden ve kabul maliyetini ekleyin.",
    changeModel: "Başka ürün seç",
    productName: "Ürün adı",
    productNamePlaceholder: "İpek Midi Elbise",
    brand: "Marka",
    brandPlaceholder: "Zimmermann",
    category: "Kategori",
    categoryPlaceholder: "Elbiseler",
    supplier: "Tedarikçi",
    supplierPlaceholder: "PINO",
    barcode: "Model barkodu (isteğe bağlı)",
    barcodePlaceholder: "869000700001",
    variantBarcode: "Varyant barkodu (isteğe bağlı)",
    gender: "Cinsiyet",
    genderNames: { women: "Kadın", men: "Erkek", unisex: "Unisex" },
    purchaseCost: "Alış maliyeti",
    currency: "Para birimi",
    color: "2 · Renk",
    colorPlaceholder: "Bir renk yazın veya seçin",
    sizes: "3 · Bedenler ve adetler",
    sizesHelp: "Kabul edilen her bedeni seçin, ardından adedini ayarlayın.",
    selectedPieces: (count: number) => `${count} adet seçildi`,
    otherSize: "Başka beden",
    addSize: "Beden ekle",
    quantity: "Adet",
    removeSize: (size: string) => `${size} bedenini kaldır`,
    saveColor: "Bu rengi kaydet ve başka renk ekle",
    draftHeading: (count: number) => `Kabul taslağı · ${count} beden satırı`,
    draftLine: (color: string, size: string) => `${color} · ${size} beden`,
    pieces: (count: number) => `${count} adet`,
    removeDraftLine: (color: string, size: string) => `${color}, ${size} beden satırını kaldır`,
    requiredFieldsHelp: "Yukarıdaki tüm zorunlu ürün alanlarını doldurun. Gri örnekler girilmiş değer değil, yalnızca ipucudur.",
    cancel: "İptal",
    saving: "Kaydediliyor…",
    receiveItems: (count: number) => `${count} ürünü kabul et`,
  },
} satisfies Record<Locale, object>;
