"use client";

import { ChevronLeft, ChevronRight, CreditCard, ReceiptText } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n";
import { Modal } from "@/components/modal";
import { CancelSaleDialog } from "./cancel-sale-dialog";
import { ExchangeFlow } from "@/features/exchanges/ui/exchange-flow";
import type { Product } from "@/lib/types";
import type { PaymentRateMap } from "../model/payments";
import { paginateSaleHistory, type SaleHistoryRecord } from "../model/sale-history";
import { filterSaleHistory, readSaleHistoryFilters, writeSaleHistoryFilters, type SaleHistoryFilters } from "../model/sale-history-filters";

const text = {
  en: { title: "Sales history", subtitle: "Store-scoped sales and reversals", empty: "No sales have been recorded for this filter yet.", status: "Confirmed", cancelled: "Cancelled", exchanged: "Exchanged", seller: "Seller", payment: "Final ticket total", line: "Sale line", details: "Sale details", close: "Close", previous: "Previous", next: "Next", items: "items", allocated: "Allocated from total sale", cancel: "Cancel sale", exchange: "Exchange item", exchangeDetails: "Item exchange", exchangedTo: "Exchanged to", topUp: "Exchange top-up", reason: "Reason", all: "All", today: "Today", week: "Wed–Tue week", period: "Period", sellerFilter: "Seller", statusFilter: "Status" },
  tr: { title: "Satış geçmişi", subtitle: "Mağazaya ait satışlar ve iptaller", empty: "Bu filtre için satış kaydı yok.", status: "Onaylandı", cancelled: "İptal edildi", exchanged: "Değiştirildi", seller: "Satıcı", payment: "Son fiş toplamı", line: "Satış satırı", details: "Satış detayları", close: "Kapat", previous: "Önceki", next: "Sonraki", items: "adet", allocated: "Toplam satıştan dağıtıldı", cancel: "Satışı iptal et", exchange: "Ürünü değiştir", exchangeDetails: "Ürün değişimi", exchangedTo: "Yeni ürün", topUp: "Değişim ek ödemesi", reason: "Neden", all: "Tümü", today: "Bugün", week: "Çar–Sal hafta", period: "Dönem", sellerFilter: "Satıcı", statusFilter: "Durum" },
} as const;

export function SaleHistory({ locale, records, sellerScope, canCancel = false, onCancel, canExchange = false, products = [], paymentRates, onExchange }: { locale: Locale; records: SaleHistoryRecord[]; sellerScope?: string; canCancel?: boolean; onCancel?: (saleId: string, reason: string) => Promise<void>; canExchange?: boolean; products?: Product[]; paymentRates?: PaymentRateMap; onExchange?: (source: SaleHistoryRecord, input: { replacement: Product; price: number; currency: "EUR" | "USD" | "TRY" | "RUB" | "GBP"; reason: string; method: "cash" | "card" | "bank_transfer"; topUpEur: number; paymentCurrency: "EUR" | "USD" | "TRY" | "RUB" | "GBP"; paymentAmount: number }) => Promise<void> }) {
  const copy = text[locale];
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<SaleHistoryRecord | null>(null);
  const [cancelTarget, setCancelTarget] = useState<SaleHistoryRecord | null>(null);
  const [exchangeTarget, setExchangeTarget] = useState<SaleHistoryRecord | null>(null);
  const [filters, setFilters] = useState<SaleHistoryFilters>(() => readSaleHistoryFilters(typeof window === "undefined" ? "" : window.location.search, sellerScope));
  const filtered = useMemo(() => filterSaleHistory(records, { ...filters, sellerId: sellerScope ?? filters.sellerId }), [filters, records, sellerScope]);
  const result = useMemo(() => paginateSaleHistory(filtered, page), [filtered, page]);
  useEffect(() => setPage(1), [records]);
  useEffect(() => { if (sellerScope) setFilters((current) => ({ ...current, sellerId: sellerScope })); }, [sellerScope]);
  const updateFilters = (next: SaleHistoryFilters) => { const scoped = { ...next, sellerId: sellerScope ?? next.sellerId }; setFilters(scoped); writeSaleHistoryFilters(scoped); };
  const sellers = [...new Map(records.map((record) => [String(record.sellerId), record.seller])).entries()];

  return <section id="sales" className="panel mt-4 scroll-mt-24 overflow-hidden rounded-2xl">
    <div className="flex items-start justify-between gap-4 border-b border-zinc-800/80 p-5 sm:p-6"><div><div className="flex items-center gap-2"><ReceiptText size={17} className="text-violet-400" /><h2 className="text-sm font-semibold">{copy.title}</h2></div><p className="mt-1 text-xs text-zinc-600">{copy.subtitle}</p></div><span className="rounded-md border border-zinc-800 px-2 py-1 text-[10px] text-zinc-400">{filtered.length} {copy.items}</span></div><div className="grid gap-2 border-b border-zinc-800/70 p-4 sm:grid-cols-3">{!sellerScope && <label className="text-[10px] font-semibold uppercase tracking-wide text-zinc-500">{copy.sellerFilter}<select aria-label={copy.sellerFilter} value={filters.sellerId} onChange={(event) => updateFilters({ ...filters, sellerId: event.target.value })} className="mt-1 h-9 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-2 text-xs text-zinc-200"><option value="all">{copy.all}</option>{sellers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>}<label className="text-[10px] font-semibold uppercase tracking-wide text-zinc-500">{copy.statusFilter}<select aria-label={copy.statusFilter} value={filters.status} onChange={(event) => updateFilters({ ...filters, status: event.target.value as SaleHistoryFilters["status"] })} className="mt-1 h-9 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-2 text-xs text-zinc-200"><option value="all">{copy.all}</option><option value="confirmed">{copy.status}</option><option value="cancelled">{copy.cancelled}</option></select></label><label className="text-[10px] font-semibold uppercase tracking-wide text-zinc-500">{copy.period}<select aria-label={copy.period} value={filters.period} onChange={(event) => updateFilters({ ...filters, period: event.target.value as SaleHistoryFilters["period"] })} className="mt-1 h-9 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-2 text-xs text-zinc-200"><option value="all">{copy.all}</option><option value="today">{copy.today}</option><option value="week">{copy.week}</option></select></label></div>
    {!filtered.length ? <p className="px-5 py-12 text-center text-xs text-zinc-600">{copy.empty}</p> : <><div className="divide-y divide-zinc-800/70">{result.items.map((sale) => { const cancelled = sale.status === "cancelled"; const status = cancelled ? copy.cancelled : sale.exchange ? copy.exchanged : copy.status; return <button key={sale.id} type="button" onClick={() => setSelected(sale)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-zinc-900/55 sm:px-6"><span className="min-w-0"><span className="block truncate text-xs font-medium text-zinc-200">{sale.exchange?.replacementProduct ?? sale.product} <span className="text-zinc-500">· {sale.exchange?.replacementCode ?? sale.code} · {sale.exchange?.replacementSize ?? sale.size}</span></span><span className="mt-1 block text-[10px] text-zinc-600">{sale.seller} · {sale.time} · {sale.quantity} {copy.items}</span></span><span className="shrink-0 text-right"><span className="block text-xs font-semibold text-zinc-100">{sale.paymentSnapshot}</span><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-[9px] font-semibold ${cancelled ? "border-amber-500/25 bg-amber-500/10 text-amber-300" : sale.exchange ? "border-violet-500/30 bg-violet-500/10 text-violet-200" : "border-emerald-500/25 bg-emerald-500/10 text-emerald-300"}`}>{status}</span></span></button>; })}</div>{result.pageCount > 1 && <div className="flex items-center justify-between border-t border-zinc-800/80 px-5 py-3"><span className="text-[10px] text-zinc-600">{result.page} / {result.pageCount}</span><div className="flex gap-2"><button type="button" aria-label={copy.previous} disabled={result.page === 1} onClick={() => setPage((value) => value - 1)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-zinc-800 text-zinc-400 disabled:opacity-35"><ChevronLeft size={15} /></button><button type="button" aria-label={copy.next} disabled={result.page === result.pageCount} onClick={() => setPage((value) => value + 1)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-zinc-800 text-zinc-400 disabled:opacity-35"><ChevronRight size={15} /></button></div></div>}</>}
    {selected && <Modal title={copy.details} eyebrow={`${copy.line} · ${selected.saleId}`} onClose={() => setSelected(null)} closeLabel={copy.close}><div className="p-5 sm:p-7"><h3 className="text-lg font-semibold">{selected.exchange?.replacementProduct ?? selected.product}</h3><p className="mt-1 text-xs text-zinc-500">{selected.exchange?.replacementCode ?? selected.code} · {selected.exchange?.replacementSize ?? selected.size}</p><dl className="mt-6 space-y-3 border-t border-zinc-800 pt-4 text-xs"><div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.seller}</dt><dd className="text-right text-zinc-200">{selected.seller}</dd></div>{selected.exchange && <><div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.exchangedTo}</dt><dd className="text-right text-zinc-200">{selected.exchange.replacementProduct} · {selected.exchange.replacementSize}</dd></div><div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.topUp}</dt><dd className="text-right text-violet-200">€{selected.exchange.topUpEur.toFixed(2)}{selected.exchange.paymentSnapshot ? ` · ${selected.exchange.paymentSnapshot}` : ""}</dd></div><div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.reason}</dt><dd className="text-right text-zinc-200">{selected.exchange.reason}</dd></div></>}<div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.payment}</dt><dd className="flex items-center gap-1.5 text-right text-zinc-200"><CreditCard size={13} />{selected.paymentSnapshot}</dd></div><div className="flex justify-between gap-4"><dt className="text-zinc-500">{copy.status}</dt><dd className={selected.status === "cancelled" ? "text-amber-300" : selected.exchange ? "text-violet-200" : "text-emerald-300"}>{selected.status === "cancelled" ? copy.cancelled : selected.exchange ? copy.exchanged : copy.status}</dd></div>{selected.revenueIsAllocated && <p className="text-[10px] text-zinc-500">{copy.allocated}</p>}</dl><div className="mt-6 flex flex-wrap gap-2">{canExchange && selected.status === "confirmed" && !selected.exchange && !selected.revenueIsAllocated && onExchange && paymentRates && <button type="button" onClick={() => { setExchangeTarget(selected); setSelected(null); }} className="min-h-10 rounded-lg border border-violet-500/40 px-4 text-xs font-semibold text-violet-200 transition hover:bg-violet-500/10">{copy.exchange}</button>}{canCancel && selected.status === "confirmed" && !selected.exchange && onCancel && <button type="button" onClick={() => { setCancelTarget(selected); setSelected(null); }} className="min-h-10 rounded-lg border border-red-500/40 px-4 text-xs font-semibold text-red-300 transition hover:bg-red-500/10">{copy.cancel}</button>}</div></div></Modal>}
    {cancelTarget && onCancel && <CancelSaleDialog locale={locale} sale={cancelTarget} onClose={() => setCancelTarget(null)} onConfirm={async (saleId, reason) => { await onCancel(saleId, reason); setCancelTarget(null); }} />}
    {exchangeTarget && onExchange && paymentRates && <Modal title={copy.exchangeDetails} eyebrow={`${copy.line} · ${exchangeTarget.saleId}`} onClose={() => setExchangeTarget(null)} closeLabel={copy.close}><ExchangeFlow locale={locale} source={exchangeTarget} products={products} rates={paymentRates} onComplete={async (input) => { await onExchange(exchangeTarget, input); setExchangeTarget(null); }} /></Modal>}
  </section>;
}
