"use client";

import { useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n";
import type { Product } from "@/lib/types";

export function InventoryCountForm({ locale, products, onConfirm }: { locale: Locale; products: Product[]; onConfirm: (lines: { variantId?: string; productId: Product["id"]; countedQuantity: number }[], notes: string) => Promise<void> }) {
  const tr = locale === "tr";
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(products.map((product) => [String(product.id), String(product.stock)])));
  const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const lines = useMemo(() => products.map((product) => ({ product, value: values[String(product.id)] ?? "" })), [products, values]);
  const submit = async () => { const parsed = lines.map(({ product, value }) => ({ variantId: product.variantId, productId: product.id, countedQuantity: Number(value) })); if (parsed.some((line) => !Number.isInteger(line.countedQuantity) || line.countedQuantity < 0)) { setError(tr ? "Her miktar sıfır veya daha büyük tam sayı olmalıdır." : "Each quantity must be a non-negative whole number."); return; } setSaving(true); setError(""); try { await onConfirm(parsed, notes); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to confirm count."); } finally { setSaving(false); } };
  return <div className="p-5 sm:p-7"><p className="text-xs leading-relaxed text-zinc-500">{tr ? "Gerçek adedi girin. Sistem yalnızca fark için denetlenebilir stok düzeltmesi oluşturur." : "Enter the physical quantity. The system creates auditable stock adjustments only for differences."}</p><div className="mt-5 max-h-[48vh] divide-y divide-zinc-800 overflow-y-auto rounded-xl border border-zinc-800">{lines.map(({ product, value }) => <label key={String(product.id)} className="flex items-center gap-3 p-3"><span className="min-w-0 flex-1"><span className="block truncate text-xs text-zinc-200">{product.name}</span><span className="mt-1 block text-[10px] text-zinc-600">{product.code} · {product.color} · {product.size} · {tr ? "sistem" : "system"}: {product.stock}</span></span><input aria-label={`${product.name} ${product.size}`} inputMode="numeric" value={value} onChange={(event) => setValues((current) => ({ ...current, [String(product.id)]: event.target.value }))} className="h-10 w-20 rounded-lg border border-zinc-800 bg-zinc-900 px-2 text-center text-sm text-zinc-100 outline-none focus:border-violet-500" /></label>)}</div><label className="mt-4 block"><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-zinc-500">{tr ? "Notlar" : "Notes"}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} className="mt-2 w-full rounded-lg border border-zinc-800 bg-zinc-900 p-3 text-xs text-zinc-100 outline-none focus:border-violet-500" /></label>{error && <p role="alert" className="mt-3 text-xs text-red-300">{error}</p>}<button type="button" disabled={saving || !products.length} onClick={() => void submit()} className="mt-5 flex h-11 w-full items-center justify-center rounded-xl bg-violet-600 text-xs font-semibold text-white disabled:opacity-50">{saving ? (tr ? "Kaydediliyor…" : "Saving…") : (tr ? "Sayımı onayla" : "Confirm count")}</button></div>;
}
